name: Deploy Production

on:
  push:
    branches:
      - v1-snapshot

jobs:
  diff:
    name: Preview stacks diff
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OIDC Login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::033662022620:role/oidc/cdk-cicd-worldid-prod
          role-session-name: worldid-dev-portal-production-oidc-session
          aws-region: us-east-1
          mask-aws-account-id: false
          role-skip-session-tagging: true
      - name: Install node modules
        run: yarn install
        working-directory: infrastructure
      - name: Install CDK globally
        run: yarn global add aws-cdk
      - name: Diff CDK stacks
        uses: ottofeller/github-actions/npm-run@main
        with:
          command: cdk diff --all --context stage=production --require-approval never
          directory: infrastructure

  deploy:
    name: Deploy stacks
    needs: [diff]
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OIDC Login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::033662022620:role/oidc/cdk-cicd-worldid-prod
          role-session-name: worldid-dev-portal-production-oidc-session
          aws-region: us-east-1
          mask-aws-account-id: false
          role-skip-session-tagging: true
      - name: Install node modules
        run: yarn install
        working-directory: infrastructure
      - name: Install CDK globally
        run: yarn global add aws-cdk
      - name: Deploy CDK stacks
        run: cdk deploy --all --context stage=production --require-approval never
        working-directory: infrastructure
      - name: Install Hasura CLI
        run: |
          yarn global add hasura-cli@2.12.0
      - name: Apply DB migrations
        run: |
          cd hasura
          hasura migrate apply --endpoint=https://api.legacy.developer.worldcoin.org/ --admin-secret='${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}' --all-databases
          hasura metadata apply --endpoint=https://api.legacy.developer.worldcoin.org/ --admin-secret='${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
          hasura metadata reload --endpoint=https://api.legacy.developer.worldcoin.org/ --admin-secret='${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}'
